### ISSUE TITLE
I made an error in the process of using, resulting in a large number of log files

### ISSUE THREAD

**Issue by yimengZJl** [odoodo/Mirth-MetaAppender#2]
![image](https://user-images.githubusercontent.com/34049542/168231896-f9409729-b84a-443d-a89e-240bffc00d42.png)

**Comment by yimengZJl** [comment]
![image](https://user-images.githubusercontent.com/34049542/168235730-9bf2fcc3-a88d-48dc-a0d2-347d948d3566.png)
![image](https://user-images.githubusercontent.com/34049542/168235746-ee6363aa-6a02-4251-8b81-9921ae14c153.png)
[mirthErrors.log](https://github.com/odoodo/Mirth-MetaAppender/files/8685126/mirthErrors.log)

**Comment by odoodo** [comment]
This behavior is normal as you set the max number of log files to 20 (3rd parameter). You did not set the max size per logfile (2nd parameter). 

So set the 2nd parameter to a value like '5MB' (see description of this extension) and your number of logs won't increase that fast.
