### ISSUE TITLE
Server log messages

### ISSUE THREAD

**Issue by steveFuturePerfect** [odoodo/Mirth-MetaAppender#4]
Hi,

Followed instructions, I've installed the jar etc and its working well.

The server log shows some messages I'm not too sure about, some not related to any channel. They're not casuing an issue, as far as I can see, but is there any way to stop these messages being logged?

For example:

_[2023-04-17 01:08:19,510]  WARN  (com.zaxxer.hikari.pool.HikariPool:616): HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=27m15s595ms964µs600ns)._

[2_023-04-12 04:06:15,166]  INFO  (test_channel-org.quartz.core.QuartzScheduler:534): Scheduler 6d037869-e8ac-45fc-8425-87050f95f834_$_NON_CLUSTERED started._
I think this is related to the use of the javascript reader connector and polling.

Thanks

**Comment by jonbartels** [comment]
Were you receiving these errors prior to installing the MetaAppender?

I think this would be better asked at https://github.com/nextgenhealthcare/connect . It does look like a general problem with the MC DB pool connections (hikari) and the scheduler (quartz).

**Comment by steveFuturePerfect** [comment]
Thanks for your reply Jon.

I wasn't seeing these messages prior to installing the MetaAppender I'll take the issue up in the /connect repository

Steve

**Comment by jonbartels** [comment]
Cross linking the posts - https://github.com/nextgenhealthcare/connect/issues/5753

**Comment by odoodo** [comment]
regarding the cross-referenced issue (thx @jonbartels) this is not a MetaAppender-issue.
